os: linux
dist: xenial
language: java
jdk:
- openjdk8
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
env:
  global:
  - secure: gNM+x1XmDOxYHxI/DaIrADyNgW4HElp+rNnh0Eq1oDYuZGHwAnL/W4R0YBunwpwv2WmfvYbs+zQk9BRjX395tKTiQT43wYj0FD8AeGi1mxpMGPrnhDF7jqLG917q1GtgA0y8sR1PB9OGNd7b1UqooFrUvfp2vN52JY9O9uQ1Xlc=
  - secure: eD8nF5iu7WL9x3wW1dZieCQEo3IIE3Cu/u8aNlC15qhlabAn2q3UrxzsR8HaKBdew9+KHwasSNIHgFnJ1xeeStVvXIBLWJn3cpH5D35qHNWbsYIJm9T6/k9ELOtu/+TmL+GkTqx7G5DcKifwuLQMSSiO3pGlEcNTKHQIfsIpjmI=
  - secure: M4HQpA/h8inmf1u1vX5Lyu19g/CpqkkwOL8ygWas9e8h15FfHYusFjSZU1XwkIfpthREVTgmyqe6iKhNr4o5np0ibVW2KnL3ocTVgRE+AMHi4IGQaOwe41KfBQPv/kpFe9xOonObakkTYze92qlFBOg3PNKVZ04MzUSObNUPBak=
  - secure: jmCvXjOA/G5J0t39N9Tm1Yi/LtmxbeFL4vAc+AXBLxvDRoqXSLCa6gRgU3ydN6YWi6aTrp09v3MgIcZwTn/QaDT5e26AgxWrUz7VQq9+oW7eOf4AF2+wj15jVVWizb/3dMzFEvQ4VAjctXhgvS5tfpsyJjFZulat4PU6AXCRdvA=
  - secure: ggaGSpMzlclKze/vk0kxqW01HoACaHB62U7I4gwOnMJMP3sD0VDFEGQI6M3vRQkoULO09y8kAM18mBRMfuhMXN1PtZqhH2v6mAlnki6r0w+DEstbRE0ajVicvLA4UAwtKDKROhnrviwJCpAHMaq6btThA1M4ANCH23W243nViyc=
  - secure: k498rYWHjDBiUvjXWk9p0aLWYfixeWp3316bLL1hx5bKy7tIG4D+IKxPu22xApzARizvxC13L0fGM1WCVOK2UEhiuJ1Q9TLPPZKydUz5hnRX/rnhoKC9XCG1EJ3P7PXSXVv3Tf4HkXeql6X9zlU66mw2MyFrmEri6JQzHt/4tQw=
cache:
  directories:
  - "$HOME/.gradle/caches"
